use shortened filepaths for Links component and route. Planning to use rollup plugin alias, but this is not working.
Last errors:

`'LinksList.svelte' is imported by src/routes/featured-topics/index.md, but could not be resolved – treating it as an external dependency` for all uses of LinksList.svelte in client and server

'LinksList.json.js' is imported by src/routes/featured-topics/index.json.js, but could not be resolved – treating it as an external dependency
'LinksList.json.js' is imported by src/routes/categories/index.json.js, but could not be resolved – treating it as an external dependency
'LinksList.json.js' is imported by src/routes/categories/clean-air-team/index.json.js, but could not be resolved – treating it as an external dependency

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'LinksList.json.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/ross/misc_coding_projects/jack-christensen/jack-c-svelte/__sapper__/dev/server/server.js:11:25)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
> Server crashed